#!/bin/sh
#
# AUTOR: PK Ernandes
# EMAIL: suporte@ernandes.info
#
#


set -e
BINDIR="/usr/local/bin"

# instalar:
for file in $(ls -1 ./src); do
  install -D -m 0755 ./src/${file} ${BINDIR}/${file}
done


# vim:set ts=2 sts=2 sw=2 et ft=sh:
