#!/bin/sh
#
# AUTOR: PK Ernandes
# EMAIL: suporte@ernandes.info
#
#


if [ "$1" = "?" ] || [ "$1" = "help" ]; then
  echo -e "\n show linux information.\n"
else
  set --
#  test -f "/etc/os-release" && echo; cat /etc/os-release; echo || echo ' error - file "/etc/os-release" not found!\n'
  if test -f "/etc/os-release"; then
    . /etc/os-release
    hostname=$(hostname)
    machine_id=$(head -n1 /etc/machine-id)
    if [ -f /etc/machine-id ] || [ "$1" = "help" ]; then
      machine_id=$(head -n1 /etc/machine-id)
    else
      machine_id="-"
    fi
    set -- "name;$NAME" \
    "version;$VERSION_ID" \
    "hostname;$hostname" \
    "machine-id;$machine_id"
  else
    set -- "error;file "/etc/os-release" not found!"
  fi

  echo
  printf "%s\n" "----;-----" "${@}" | column -t -s';' --table-columns name,value; echo
fi


# vim:set ts=2 sts=2 sw=2 et ft=sh:
